"""add resume_scores table and resume.analysis_error

Revision ID: 2abc4c2babe0
Revises: 326993c9dd64
Create Date: 2026-08-12 23:09:14.248334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2abc4c2babe0'
down_revision: Union[str, None] = '326993c9dd64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_scores',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('job_role_id', sa.UUID(), nullable=True),
    sa.Column('job_description_id', sa.UUID(), nullable=True),
    sa.Column('ats_score', sa.Float(), nullable=False),
    sa.Column('matched_ats_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_skill_match', sa.Float(), nullable=False),
    sa.Column('matched_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('experience_match', sa.Float(), nullable=False),
    sa.Column('candidate_experience_years', sa.Float(), nullable=True),
    sa.Column('suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_scores_job_description_id'), 'resume_scores', ['job_description_id'], unique=False)
    op.create_index(op.f('ix_resume_scores_job_role_id'), 'resume_scores', ['job_role_id'], unique=False)
    op.create_index(op.f('ix_resume_scores_resume_id'), 'resume_scores', ['resume_id'], unique=True)
    op.add_column('resumes', sa.Column('analysis_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'analysis_error')
    op.drop_index(op.f('ix_resume_scores_resume_id'), table_name='resume_scores')
    op.drop_index(op.f('ix_resume_scores_job_role_id'), table_name='resume_scores')
    op.drop_index(op.f('ix_resume_scores_job_description_id'), table_name='resume_scores')
    op.drop_table('resume_scores')
    # ### end Alembic commands ###
