"""initial schema

Revision ID: 326993c9dd64
Revises: 
Create Date: 2026-08-10 22:35:07.296477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '326993c9dd64'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('linkedin_url', sa.String(length=400), nullable=True),
    sa.Column('github_url', sa.String(length=400), nullable=True),
    sa.Column('portfolio_url', sa.String(length=400), nullable=True),
    sa.Column('total_experience_years', sa.Float(), nullable=True),
    sa.Column('current_title', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=False)
    op.create_table('job_roles',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('default_level', sa.String(length=20), nullable=False),
    sa.Column('min_experience_years', sa.Float(), nullable=False),
    sa.Column('max_experience_years', sa.Float(), nullable=True),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferred_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nice_to_have_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('responsibilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ats_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scoring_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_roles_active_title', 'job_roles', ['is_active', 'title'], unique=False)
    op.create_index(op.f('ix_job_roles_slug'), 'job_roles', ['slug'], unique=True)
    op.create_table('job_descriptions',
    sa.Column('job_role_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parse_status', sa.String(length=20), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_descriptions_job_role_id'), 'job_descriptions', ['job_role_id'], unique=False)
    op.create_index(op.f('ix_job_descriptions_parse_status'), 'job_descriptions', ['parse_status'], unique=False)
    op.create_table('screening_batches',
    sa.Column('job_role_id', sa.UUID(), nullable=False),
    sa.Column('job_description_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('recruiter_email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_resumes', sa.Integer(), nullable=False),
    sa.Column('parsed_resumes', sa.Integer(), nullable=False),
    sa.Column('failed_resumes', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_batches_job_description_id'), 'screening_batches', ['job_description_id'], unique=False)
    op.create_index(op.f('ix_screening_batches_job_role_id'), 'screening_batches', ['job_role_id'], unique=False)
    op.create_index(op.f('ix_screening_batches_recruiter_email'), 'screening_batches', ['recruiter_email'], unique=False)
    op.create_index(op.f('ix_screening_batches_status'), 'screening_batches', ['status'], unique=False)
    op.create_table('resumes',
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('job_role_id', sa.UUID(), nullable=True),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('upload_source', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=600), nullable=False),
    sa.Column('file_extension', sa.String(length=16), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parse_status', sa.String(length=20), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analysis_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['screening_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'content_hash', name='uq_resume_batch_content')
    )
    op.create_index(op.f('ix_resumes_analysis_status'), 'resumes', ['analysis_status'], unique=False)
    op.create_index(op.f('ix_resumes_batch_id'), 'resumes', ['batch_id'], unique=False)
    op.create_index(op.f('ix_resumes_candidate_id'), 'resumes', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_resumes_content_hash'), 'resumes', ['content_hash'], unique=False)
    op.create_index(op.f('ix_resumes_job_role_id'), 'resumes', ['job_role_id'], unique=False)
    op.create_index(op.f('ix_resumes_parse_status'), 'resumes', ['parse_status'], unique=False)
    op.create_index('ix_resumes_role_status', 'resumes', ['job_role_id', 'parse_status'], unique=False)
    op.create_index(op.f('ix_resumes_upload_source'), 'resumes', ['upload_source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumes_upload_source'), table_name='resumes')
    op.drop_index('ix_resumes_role_status', table_name='resumes')
    op.drop_index(op.f('ix_resumes_parse_status'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_job_role_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_content_hash'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_candidate_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_batch_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_analysis_status'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_screening_batches_status'), table_name='screening_batches')
    op.drop_index(op.f('ix_screening_batches_recruiter_email'), table_name='screening_batches')
    op.drop_index(op.f('ix_screening_batches_job_role_id'), table_name='screening_batches')
    op.drop_index(op.f('ix_screening_batches_job_description_id'), table_name='screening_batches')
    op.drop_table('screening_batches')
    op.drop_index(op.f('ix_job_descriptions_parse_status'), table_name='job_descriptions')
    op.drop_index(op.f('ix_job_descriptions_job_role_id'), table_name='job_descriptions')
    op.drop_table('job_descriptions')
    op.drop_index(op.f('ix_job_roles_slug'), table_name='job_roles')
    op.drop_index('ix_job_roles_active_title', table_name='job_roles')
    op.drop_table('job_roles')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
